name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build && cd dist && echo > .nojekyll

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: management_client.wangminan.me

      - name: 开始部署镜像站
        run: echo "开始部署镜像站"


      - name: 删除旧的dist
        run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "cd ~/management_client/ && rm -rf ./dist"

      - name: 上传新的dist包到服务器中
        run: ls && sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./dist root@${{secrets.REMOTE_IP}}:~/management_client/
